# Generated by Django 5.1 on 2024-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
